import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  bookSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1 – The Robotic Nervous System (ROS 2)',
      link: {type: 'doc', id: 'module1-ros2/index'},
      items: [{type: 'autogenerated', dirName: 'module1-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2 – The Digital Twin (Gazebo & Unity)',
      link: {type: 'doc', id: 'module2-digital-twin/index'},
      items: [{type: 'autogenerated', dirName: 'module2-digital-twin'}],
    },
    {
      type: 'category',
      label: 'Module 3 – The AI-Robot Brain (NVIDIA Isaac™ Platform)',
      link: {type: 'doc', id: 'module3-isaac-platform/index'},
      items: [{type: 'autogenerated', dirName: 'module3-isaac-platform'}],
    },
    {
      type: 'category',
      label: 'Module 4 – Vision-Language-Action (VLA) & Conversational Humanoids',
      link: {type: 'doc', id: 'module4-vla/index'},
      items: [{type: 'autogenerated', dirName: 'module4-vla'}],
    },
    {
      type: 'category',
      label: 'Appendices',
      link: {type: 'doc', id: 'appendices/index'},
      items: [{type: 'autogenerated', dirName: 'appendices'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
